name: build
# Correr manualmente:
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install GO
        # Uso variable que cargue en settings. 
        run: echo "${{ vars.JOB_BUILD_NAME }}"
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
      - name: Check Go
        run: | 
            echo "Your version of GO is: "
            go version
  second_job :
    runs-on: ubuntu
    steps:
      - name: Install Python
        uses: actions/setup-python@v5.1.0 
        with:
            python-version: 3.10
            
