name: build
# Correr manualmente:
on: workflow_dispatch
jobs:
  first-step:
    # name: ${{ vars.JOB_BUILD_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        # Uso variable que cargue en settings. 
        run: echo "${{ vars.JOB_BUILD_NAME }}"
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
      - name: Test Go
        run: | 
            echo "a veeeeer"
            go version
          
