name: build
on: workflow_dispatch
jobs:
  first-step:
    # name: ${{ vars.JOB_BUILD_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "${{ vars.JOB_BUILD_NAME }}"
